#!/bin/sh

if [ $# = 0 ]; then
    echo "Please input steps, such as ./verify b0"
    exit 0;
fi

for step in "$@"; do
    case $step in
        b0)
            make clean && make STEP=b0 run | tee /tmp/b0
            ;;
        b2)
            make clean && make STEP=b2 run | tee /tmp/b2
            ;;
        *)
            echo 'no such step'
            ;;
    esac
done

